# CUTLASS #2906: explicit TMA member alignment for NVCC/MSVC.
function(ggml_cuda_cutlass_align_member path before after)
    file(READ "${path}" contents)
    string(FIND "${contents}" "${after}" patched)
    if(NOT patched EQUAL -1)
        return()
    endif()
    string(FIND "${contents}" "${before}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "CUTLASS alignment patch no longer matches ${path}: ${before}")
    endif()
    string(REPLACE "${before}" "${after}" contents "${contents}")
    file(WRITE "${path}" "${contents}")
endfunction()

set(ggml_cutlass_mainloop "${cutlass_SOURCE_DIR}/include/cutlass/gemm/collective/sm120_blockscaled_mma_tma.hpp")
set(ggml_cutlass_epilogue "${cutlass_SOURCE_DIR}/include/cutlass/epilogue/collective/sm90_epilogue_tma_warpspecialized.hpp")
foreach(header IN ITEMS "${ggml_cutlass_mainloop}" "${ggml_cutlass_epilogue}")
    ggml_cuda_cutlass_align_member("${header}" "  struct Params {" "  struct alignas(64) Params {")
endforeach()
foreach(member IN ITEMS "TMA_A tma_load_a" "TMA_B tma_load_b" "TMA_SFA tma_load_sfa" "TMA_SFB tma_load_sfb")
    ggml_cuda_cutlass_align_member("${ggml_cutlass_mainloop}" "    ${member};" "    alignas(64) ${member};")
endforeach()
foreach(member IN ITEMS "TMA_C tma_load_c" "TMA_D tma_store_d")
    ggml_cuda_cutlass_align_member("${ggml_cutlass_epilogue}" "    ${member};" "    alignas(64) ${member};")
endforeach()
